### PR TITLE
Add frameOrigin, frameSize, boundsOrigin, boundsSize properties

### LINKED ISSUE #2: frameOrigin, frameSize, boundsOrigin, boundsSize
More animatable properties for `NSView`.

### PR DESCRIPTION
**Pull request by akashivskyy**
Adds the following, ~~cross-platform~~ properties:
- `frameOrigin: CGPoint`
- `frameSize: CGSize`
- `boundsOrigin: CGPoint`
- `boundsSize: CGSize`

Resolves #2.

### CODE REVIEW

**Comment by akashivskyy** [comment]
I just noticed that #2 is labeled with `mac`. Should those properties be only available for OS X deployment or can they stay cross-platform?

**Comment by jspahrsummers** [comment]
Thanks for the pull request!

I'm hesitant to add these properties for iOS, because I think reading existing values could cause problems (for example, if you have multiple signals bound to different parts of the view's frame).

It might make sense in the future, but I think I'd like these to be OS X only for now.

**Comment by akashivskyy** [comment]
I see your point, @jspahrsummers. Fixed it. :wink:

**Comment by jspahrsummers** [comment]
Thanks! :heart:

**Pull request merged**
